package com.ezirs.ui.theme
import androidx.compose.ui.graphics.Color
val md_theme_primary = Color(0xFF6750A4)
val md_theme_onPrimary = Color(0xFFFFFFFF)
val md_theme_primaryContainer = Color(0xFFEADDFF)
val md_theme_onPrimaryContainer = Color(0xFF21005D)
val md_theme_secondaryContainer = Color(0xFFE8DEF8)
val md_theme_onSecondaryContainer = Color(0xFF1D192B)
val md_theme_error = Color(0xFFB3261E)
val md_theme_onError = Color(0xFFFFFFFF)
val md_theme_background = Color(0xFFFEF7FF)
val md_theme_onBackground = Color(0xFF1D1B20)
val md_theme_surface = Color(0xFFFEF7FF)
val md_theme_onSurface = Color(0xFF1D1B20)
val md_theme_surfaceVariant = Color(0xFFF3EDF7)
val md_theme_onSurfaceVariant = Color(0xFF49454F)
val md_theme_outline = Color(0xFFCAC4D0)
val md_theme_outlineVariant = Color(0xFFE7E0EC)

val dark_md_theme_primary = Color(0xFFD0BCFF)
val dark_md_theme_onPrimary = Color(0xFF381E72)
val dark_md_theme_primaryContainer = Color(0xFF4F378B)
val dark_md_theme_onPrimaryContainer = Color(0xFFEADDFF)
val dark_md_theme_secondaryContainer = Color(0xFF4A4458)
val dark_md_theme_onSecondaryContainer = Color(0xFFE8DEF8)
val dark_md_theme_error = Color(0xFFF2B8B5)
val dark_md_theme_onError = Color(0xFF601410)
val dark_md_theme_background = Color(0xFF141218)
val dark_md_theme_onBackground = Color(0xFFE6E0E9)
val dark_md_theme_surface = Color(0xFF141218)
val dark_md_theme_onSurface = Color(0xFFE6E0E9)
val dark_md_theme_surfaceVariant = Color(0xFF49454F)
val dark_md_theme_onSurfaceVariant = Color(0xFFCAC4D0)
val dark_md_theme_outline = Color(0xFF938F99)
val dark_md_theme_outlineVariant = Color(0xFF49454F)
